apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_LINK:cG9zdGdyZXNxbDovL3Bvc3RncmVzOkFkbWluMTIzZGF0YWJhc2UtMS5jcmdhODBtaW8xc2cuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Bvc3RncmVz