apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_LINK: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkFkbWluMTIzJEBzdHVkZW50LXBvcnRhbC5jcmdhODBtaW8xc2cuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL215ZGI=