name: GitHub action that uses the shell commands, needs and environment variables

on:
  workflow_dispatch:
  # This allows manual triggering of the workflow with an input parameter
  # Getting user input
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      user_name: ${{ steps.set-name.outputs.user_name }}
    steps:
      - name: Set user name from input
        id: set-name
        run: echo "user_name=${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT
  # This job sets the user name based on the input provided when the workflow is triggered
  hello:
    runs-on: ubuntu-latest
    needs: greet
    env:
      USER_NAME: ${{ needs.greet.outputs.user_name }}
    steps:
      - name: Say hello
        run: echo "Hello, ${{ env.USER_NAME }}!"
  # This job depends on the previous job and set the environment variable USER_NAME
      # It then prints a greeting message using the user name set in the previous job
      