name: Demo GitHub Action Workflow

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: "Name of the folder to check"
        required: true
        default: "my-folder"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      folder: ${{ steps.set-folder.outputs.folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set folder from input
        id: set-folder
        run: |
         echo "folder=${{ github.event.inputs.folder_name }}" >> $GITHUB_OUTPUT

  check-folder:
    runs-on: ubuntu-latest
    needs: prepare
    env:
      TARGET_FOLDER: ${{ needs.prepare.outputs.folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display folder name from env
        run: |
         echo "Folder to check: ${{env.TARGET_FOLDER}}"

      - name: Check if folder exists
        run: |
          if [ -d ${{env.TARGET_FOLDER"}} ]; then
            echo "✅ Folder '${{env.TARGET_FOLDER}}' exists."
          else
            echo "❌ Folder '${{env.TARGET_FOLDER}}' does not exist."
            exit 1
          fi
