name: class 5 - runner types-windows

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: "Name of the folder to check"
        required: true
        default: "my-folder"

jobs:
  prepare:
    runs-on: windows-latest
    outputs:
      folder: ${{ steps.set-folder.outputs.folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set folder from input
        id: set-folder
        run: |
          echo "folder=${{ github.event.inputs.folder_name }}" >> $GITHUB_OUTPUT

  check-folder-windows:
    runs-on: windows-latest
    needs: prepare
    env:
      TARGET_FOLDER: ${{ needs.prepare.outputs.folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display folder name from env (Windows)
        shell: pwsh
        run: |
          Write-Host "Folder to check: $env:TARGET_FOLDER"

      - name: Check if folder exists (Windows)
        shell: pwsh
        run: |
          if (Test-Path -Path $env:TARGET_FOLDER -PathType Container) {
            Write-Host "✅ Folder '$env:TARGET_FOLDER' exists."
          }
          else {
            Write-Host "❌ Folder '$env:TARGET_FOLDER' does not exist."
          }
          Write-Host "Folder check completed successfully."


